<?php
return array (
  4 => 
  array (
    'id' => '4',
    'catid' => '13',
    'typeid' => '0',
    'title' => '1223の嗯嗯',
    'style' => '',
    'thumb' => 'http://localhost:3069/uploadfile/2018/0423/20180423105431488.jpg',
    'keywords' => '1223の嗯嗯',
    'description' => '帝企鹅而非v',
    'posids' => '0',
    'url' => 'http://localhost:3069/index.php?m=content&c=index&a=show&catid=13&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1524495251',
    'updatetime' => '1524641464',
    'num' => '0',
    'picture' => '',
    'location' => '',
    'hitsid' => 'c-1-4',
    'views' => '10',
    'yesterdayviews' => '8',
    'dayviews' => '2',
    'weekviews' => '10',
    'monthviews' => '10',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '13',
    'typeid' => '0',
    'title' => '12345',
    'style' => '',
    'thumb' => 'http://localhost:3069/uploadfile/2018/0423/20180423105312416.jpg',
    'keywords' => '12345',
    'description' => '蚊收点v ',
    'posids' => '0',
    'url' => 'http://localhost:3069/index.php?m=content&c=index&a=show&catid=13&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1524495163',
    'updatetime' => '1524561197',
    'num' => '0',
    'picture' => '',
    'location' => '',
    'hitsid' => 'c-1-3',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  13 => 
  array (
    'id' => '13',
    'catid' => '13',
    'typeid' => '0',
    'title' => 'vfev',
    'style' => '',
    'thumb' => '',
    'keywords' => 'vfev',
    'description' => 'vvf',
    'posids' => '0',
    'url' => 'http://localhost:3069/index.php?m=content&c=index&a=show&catid=13&id=13',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1524564628',
    'updatetime' => '1524641469',
    'num' => '0',
    'picture' => '',
    'location' => '',
    'hitsid' => 'c-1-13',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  9 => 
  array (
    'id' => '9',
    'catid' => '13',
    'typeid' => '0',
    'title' => 'vsdv',
    'style' => '',
    'thumb' => '',
    'keywords' => 'vsdv',
    'description' => 'vs',
    'posids' => '0',
    'url' => 'http://localhost:3069/index.php?m=content&c=index&a=show&catid=13&id=9',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1524564556',
    'updatetime' => '1524564569',
    'num' => '0',
    'picture' => '',
    'location' => '',
    'hitsid' => 'c-1-9',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  10 => 
  array (
    'id' => '10',
    'catid' => '13',
    'typeid' => '0',
    'title' => 'vs',
    'style' => '',
    'thumb' => '',
    'keywords' => 'vs',
    'description' => 'vs',
    'posids' => '0',
    'url' => 'http://localhost:3069/index.php?m=content&c=index&a=show&catid=13&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1524564574',
    'updatetime' => '1524564584',
    'num' => '0',
    'picture' => '',
    'location' => '',
    'hitsid' => 'c-1-10',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  11 => 
  array (
    'id' => '11',
    'catid' => '13',
    'typeid' => '0',
    'title' => 'bgb',
    'style' => '',
    'thumb' => '',
    'keywords' => 'bgb',
    'description' => 'bfgbf',
    'posids' => '0',
    'url' => 'http://localhost:3069/index.php?m=content&c=index&a=show&catid=13&id=11',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1524564599',
    'updatetime' => '1524564609',
    'num' => '0',
    'picture' => '',
    'location' => '',
    'hitsid' => 'c-1-11',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  12 => 
  array (
    'id' => '12',
    'catid' => '13',
    'typeid' => '0',
    'title' => 'vfds',
    'style' => '',
    'thumb' => '',
    'keywords' => 'vfdsvr',
    'description' => ' fggbrb',
    'posids' => '0',
    'url' => 'http://localhost:3069/index.php?m=content&c=index&a=show&catid=13&id=12',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1524564613',
    'updatetime' => '1524564623',
    'num' => '0',
    'picture' => '',
    'location' => '',
    'hitsid' => 'c-1-12',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>