<?php
return array (
  2 => 
  array (
    'id' => '2',
    'catid' => '11',
    'typeid' => '0',
    'title' => '大聪',
    'style' => '',
    'thumb' => 'http://localhost:3069/uploadfile/2018/0423/20180423105327663.jpg',
    'keywords' => '大聪',
    'description' => '简介',
    'posids' => '0',
    'url' => 'http://localhost:3069/index.php?m=content&c=index&a=show&catid=11&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1524495074',
    'updatetime' => '1524495105',
    'num' => '456.99',
    'picture' => '',
    'location' => '',
    'hitsid' => 'c-1-2',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '11',
    'typeid' => '0',
    'title' => '盛亭',
    'style' => '',
    'thumb' => 'http://localhost:3069/uploadfile/2018/0423/20180423110942248.jpg',
    'keywords' => '盛亭',
    'description' => '盛亭行馆',
    'posids' => '0',
    'url' => 'http://localhost:3069/index.php?m=content&c=index&a=show&catid=11&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1524496068',
    'updatetime' => '1524496185',
    'num' => '329',
    'picture' => '',
    'location' => '',
    'hitsid' => 'c-1-5',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '12',
    'typeid' => '0',
    'title' => '鸡蛋摊摊',
    'style' => '',
    'thumb' => 'http://localhost:3069/uploadfile/2018/0424/20180424024607618.jpg',
    'keywords' => '鸡蛋',
    'description' => '鸡蛋摊摊的摘要',
    'posids' => '0',
    'url' => 'http://localhost:3069/index.php?m=content&c=index&a=show&catid=12&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1524552269',
    'updatetime' => '1524552370',
    'num' => '5',
    'picture' => '',
    'location' => '',
    'hitsid' => 'c-1-6',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  7 => 
  array (
    'id' => '7',
    'catid' => '12',
    'typeid' => '0',
    'title' => '焖饭',
    'style' => '',
    'thumb' => 'http://localhost:3069/uploadfile/2018/0424/20180424024731783.jpg',
    'keywords' => '焖饭',
    'description' => '焖饭的摘要',
    'posids' => '0',
    'url' => 'http://localhost:3069/index.php?m=content&c=index&a=show&catid=12&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1524552375',
    'updatetime' => '1524552454',
    'num' => '9',
    'picture' => '',
    'location' => '',
    'hitsid' => 'c-1-7',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  8 => 
  array (
    'id' => '8',
    'catid' => '12',
    'typeid' => '0',
    'title' => '美食专栏',
    'style' => '',
    'thumb' => '//upload-images.jianshu.io/upload_images/4952818-431c68c5564cc575..jpeg',
    'keywords' => '专栏 美食',
    'description' => '过桥米线：虽然不是丽江特产，但是这家的味道酸是正宗了。不要再古城吃，要到副慧路，丽江宾馆门口的桥之情正宗蒙自过桥米线店吃。鸡豆凉粉   ',
    'posids' => '0',
    'url' => 'http://localhost:3069/index.php?m=content&c=index&a=show&catid=12&id=8',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1524556122',
    'updatetime' => '1524556214',
    'num' => '23',
    'picture' => '',
    'location' => '',
    'hitsid' => 'c-1-8',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>