<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '14',
    'typeid' => '0',
    'title' => '民宿1',
    'style' => '',
    'thumb' => 'https://www.shotour.com/upload/201802/watermark/1519200927554206.jpg',
    'keywords' => '民宿',
    'description' => '锦堂为二层古典硬山式园林建筑，共有豪华单人间30间，套房4套。行馆内南临逶迤的石板老街，东接优雅的洛神SPA，北可隔河眺望天然湿地，西有',
    'posids' => '0',
    'url' => 'http://localhost:3069/index.php?m=content&c=index&a=show&catid=14&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1524532299',
    'updatetime' => '1524532434',
    'character' => '锦堂占地15000平方米，二层古典硬山式园林建筑，行馆内南临逶迤的石板老街，东接优雅的洛神SPA ，北可隔河眺望天然湿地，西有清流直通市河，地理位置极为优越。',
    'money' => '789.9',
    'hitsid' => 'c-12-1',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '14',
    'typeid' => '0',
    'title' => '韩轩亭',
    'style' => '',
    'thumb' => 'http://localhost:3069/uploadfile/2018/0424/20180424013559121.jpg',
    'keywords' => '韩轩亭',
    'description' => '这个亭子巴拉巴拉巴拉',
    'posids' => '0',
    'url' => 'http://localhost:3069/index.php?m=content&c=index&a=show&catid=14&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1524548137',
    'updatetime' => '1524548259',
    'character' => '好好好好啊',
    'money' => '333.9',
    'hitsid' => 'c-12-2',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>